---
title: "bowl_game_predictor"
author: "Tyler Iams"
date: "12/13/2018"
output: html_document
---


```{r}
library(tidyverse)
```

```{r, message=FALSE, warning=FALSE}
# 2008 data
conf_dat_2008 <- read_csv("data/2008_conf.csv")
def_dat_2008 <- read_csv("data/2008_defense.csv")
off_dat_2008 <- read_csv("data/2008_offense.csv")
game_dat_2008 <- read_csv("data/2008_games.csv")

# 2009 data
conf_dat_2009 <- read_csv("data/2009_conf.csv")
def_dat_2009 <- read_csv("data/2009_defense.csv")
off_dat_2009 <- read_csv("data/2009_offense.csv")
game_dat_2009 <- read_csv("data/2009_games.csv")

# 2010 data
conf_dat_2010 <- read_csv("data/2010_conf.csv")
def_dat_2010 <- read_csv("data/2010_defense.csv")
off_dat_2010 <- read_csv("data/2010_offense.csv")
game_dat_2010 <- read_csv("data/2010_games.csv")

#2011 data
conf_dat_2011 <- read_csv("data/2011_conf.csv")
def_dat_2011 <- read_csv("data/2011_defense.csv")
off_dat_2011 <- read_csv("data/2011_offense.csv")
game_dat_2011 <- read_csv("data/2011_games.csv")

#2012 data
conf_dat_2012 <- read_csv("data/2012_conf.csv")
def_dat_2012 <- read_csv("data/2012_defense.csv")
off_dat_2012 <- read_csv("data/2012_offense.csv")
game_dat_2012 <- read_csv("data/2012_games.csv")

#2013 data
conf_dat_2013 <- read_csv("data/2013_conf.csv")
def_dat_2013 <- read_csv("data/2013_defense.csv")
off_dat_2013 <- read_csv("data/2013_offense.csv")
game_dat_2013 <- read_csv("data/2013_games.csv")

#2014 data
conf_dat_2014 <- read_csv("data/2014_conf.csv")
def_dat_2014 <- read_csv("data/2014_defense.csv")
off_dat_2014 <- read_csv("data/2014_offense.csv")
game_dat_2014 <- read_csv("data/2014_games.csv")

#2015 data
conf_dat_2015 <- read_csv("data/2015_conf.csv")
def_dat_2015 <- read_csv("data/2015_defense.csv")
off_dat_2015 <- read_csv("data/2015_offense.csv")
game_dat_2015 <- read_csv("data/2015_games.csv")

#2016 data
conf_dat_2016 <- read_csv("data/2016_conf.csv")
def_dat_2016 <- read_csv("data/2016_defense.csv")
off_dat_2016 <- read_csv("data/2016_offense.csv")
game_dat_2016 <- read_csv("data/2016_games.csv")

#2017 data
conf_dat_2017 <- read_csv("data/2017_conf.csv")
def_dat_2017 <- read_csv("data/2017_defense.csv")
off_dat_2017 <- read_csv("data/2017_offense.csv")
game_dat_2017 <- read_csv("data/2017_games.csv")

#2018 data
conf_dat_2018 <- read_csv("data/2018_conf.csv")
def_dat_2018 <- read_csv("data/2018_defense.csv")
off_dat_2018 <- read_csv("data/2018_offense.csv")
game_dat_2018 <- read_csv("data/2018_games.csv")
```

```{r}
#conf data

# This reads the conf_teams.csv file and formats the column names, and removes subconferences, ie if a team is in SEC West, they just become SEC.  This is in order to create less levels when it is turned into a factor variable, and because we presume that differences between partitions of conferences will be negligible.

conference_list <- read_csv("data/conf_teams.csv")
conference_list <- conference_list %>% rename(School = X2, conf = X3)

conference_list <- conference_list %>% select(School, conf)
conference_list <- conference_list[-1,]
conference_list <- conference_list %>% mutate(conf = gsub("\\(West)", "", conference_list$conf))
conference_list <- conference_list %>% mutate(conf = gsub("\\(Atlantic)", "", conference_list$conf))
conference_list <- conference_list %>% mutate(conf = gsub("\\(North)", "", conference_list$conf))
conference_list <- conference_list %>% mutate(conf = gsub("\\(East)", "", conference_list$conf))
conference_list <- conference_list %>% mutate(conf = gsub("\\(South)", "", conference_list$conf))
conference_list <- conference_list %>% mutate(conf = gsub("\\(Mountain)", "", conference_list$conf))
conference_list <- conference_list %>% mutate(conf = gsub("\\(Coastal)", "", conference_list$conf))
conference_list <- conference_list %>% mutate(conf = trimws(conf))
conference_list <- conference_list %>% mutate(School = trimws(School))
```


**Functions**

**Offensive Function**

```{r}
# This formats the offensive data by renaming columns.  Column names had occupied two rows, and this simplifies column names to only occupy one row.

formatter_off <- function(off_dat) {
    off_dat <- off_dat %>% rename(off_rank = X1, Home = X2, games = X3, pts = X4, p_comp = Passing, p_att = Passing_1, comp_pct = Passing_2, p_yds = Passing_3, p_td = Passing_4, r_att = Rushing, r_yds = Rushing_1, r_avg = Rushing_2, r_td = Rushing_3, ttl_off_plays= `Total Offense`, ttl_off_yds = `Total Offense_1`, ttl_off_avg = `Total Offense_2`, pass_fd = `First Downs`, rush_fd = `First Downs_1`, pen_fd = `First Downs_2`, ttl_fd = `First Downs_3`, pen = Penalties, pen_yds = Penalties_1, fum = Turnovers, int = Turnovers_1, turnover = Turnovers_2)

off_dat <- off_dat[-1,]
}

off_dat_2008 <- formatter_off(off_dat_2008)
off_dat_2009 <- formatter_off(off_dat_2009)
off_dat_2010 <- formatter_off(off_dat_2010)
off_dat_2011 <- formatter_off(off_dat_2011)
off_dat_2012 <- formatter_off(off_dat_2012)
off_dat_2013 <- formatter_off(off_dat_2013)
off_dat_2014 <- formatter_off(off_dat_2014)
off_dat_2015 <- formatter_off(off_dat_2015)
off_dat_2016 <- formatter_off(off_dat_2016)
off_dat_2017 <- formatter_off(off_dat_2017)
off_dat_2018 <- formatter_off(off_dat_2018)
```

**Defensive Function**

```{r}
# This simplifies defensive data in the same way by taking two-row column headers and making them into single row column headers.

formatter_def <- function(def_dat)  {
    def_dat <- def_dat %>% rename(def_rank = X1, Home = X2, games = X3, opp_pts = X4, opp_p_comp = Passing, opp_p_att = Passing_1, opp_comp_pct = Passing_2, opp_p_yds = Passing_3, opp_p_td = Passing_4, opp_r_att = Rushing, opp_r_yds = Rushing_1, opp_r_avg = Rushing_2, opp_r_td = Rushing_3, opp_ttl_off_plays= `Total Offense`, opp_ttl_off_yds = `Total Offense_1`, opp_ttl_off_avg = `Total Offense_2`, opp_pass_fd = `First Downs`, opp_rush_fd = `First Downs_1`, opp_pen_fd = `First Downs_2`, opp_ttl_fd = `First Downs_3`, def_pen = Penalties, def_pen_yds = Penalties_1, opp_fum = Turnovers, opp_int = Turnovers_1, opp_turnover = Turnovers_2)

def_dat <- def_dat[-1,]
}

def_dat_2008 <- formatter_def(def_dat_2008)
def_dat_2009 <- formatter_def(def_dat_2009)
def_dat_2010 <- formatter_def(def_dat_2010)
def_dat_2011 <- formatter_def(def_dat_2011)
def_dat_2012 <- formatter_def(def_dat_2012)
def_dat_2013 <- formatter_def(def_dat_2013)
def_dat_2014 <- formatter_def(def_dat_2014)
def_dat_2015 <- formatter_def(def_dat_2015)
def_dat_2016 <- formatter_def(def_dat_2016)
def_dat_2017 <- formatter_def(def_dat_2017)
def_dat_2018 <- formatter_def(def_dat_2018)
```


```{r}
# These functions format the way the team names are presented in the game data file.  Some team names included their weekly top 25 ranking, and this would disrupt the ability to join by team name later on, so we disposed of the rankings.

formatter_game1 <- function(game_dat, year) {

  game_dat <- game_dat %>% mutate(Winner = gsub("\\(", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Winner = gsub("1", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Winner = gsub("2", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Winner = gsub("3", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Winner = gsub("4", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Winner = gsub("5", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Winner = gsub("6", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Winner = gsub("7", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Winner = gsub("8", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Winner = gsub("9", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Winner = gsub("0", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Winner = gsub(")", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Loser = gsub("\\(", "", game_dat$Loser))
  game_dat <- game_dat %>% mutate(Loser = gsub("1", "", game_dat$Loser))
  game_dat <- game_dat %>% mutate(Loser = gsub("2", "", game_dat$Loser))
  game_dat <- game_dat %>% mutate(Loser = gsub("3", "", game_dat$Loser))
  game_dat <- game_dat %>% mutate(Loser = gsub("4", "", game_dat$Loser))
  game_dat <- game_dat %>% mutate(Loser = gsub("5", "", game_dat$Loser))
  game_dat <- game_dat %>% mutate(Loser = gsub("6", "", game_dat$Loser))
  game_dat <- game_dat %>% mutate(Loser = gsub("7", "", game_dat$Loser))
  game_dat <- game_dat %>% mutate(Loser = gsub("8", "", game_dat$Loser))
  game_dat <- game_dat %>% mutate(Loser = gsub("9", "", game_dat$Loser))
  game_dat <- game_dat %>% mutate(Loser = gsub("0", "", game_dat$Loser))
  game_dat <- game_dat %>% mutate(Loser = gsub(")", "", game_dat$Loser))
  
  game_dat <- game_dat %>% mutate(X7 = ifelse(is.na(X7 == TRUE), "vs", "@"))
  game_dat <- game_dat %>% mutate(Home = ifelse(X7 == '@', Loser, Winner))
  game_dat <- game_dat %>% mutate(Away = ifelse(Home == Winner, Loser, Winner))
  game_dat <- game_dat %>% mutate(Outcome = factor(ifelse(Home == Winner, 1, 0)))
  game_dat <- game_dat %>% mutate(Year = year)
  game_dat <- game_dat %>% select(Wk, Year, Home, Away, Outcome)
}


formatter_game2 <- function(game_dat, year) {

  game_dat <- game_dat %>% mutate(Winner = gsub("\\(", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Winner = gsub("1", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Winner = gsub("2", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Winner = gsub("3", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Winner = gsub("4", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Winner = gsub("5", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Winner = gsub("6", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Winner = gsub("7", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Winner = gsub("8", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Winner = gsub("9", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Winner = gsub("0", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Winner = gsub(")", "", game_dat$Winner))
  game_dat <- game_dat %>% mutate(Loser = gsub("\\(", "", game_dat$Loser))
  game_dat <- game_dat %>% mutate(Loser = gsub("1", "", game_dat$Loser))
  game_dat <- game_dat %>% mutate(Loser = gsub("2", "", game_dat$Loser))
  game_dat <- game_dat %>% mutate(Loser = gsub("3", "", game_dat$Loser))
  game_dat <- game_dat %>% mutate(Loser = gsub("4", "", game_dat$Loser))
  game_dat <- game_dat %>% mutate(Loser = gsub("5", "", game_dat$Loser))
  game_dat <- game_dat %>% mutate(Loser = gsub("6", "", game_dat$Loser))
  game_dat <- game_dat %>% mutate(Loser = gsub("7", "", game_dat$Loser))
  game_dat <- game_dat %>% mutate(Loser = gsub("8", "", game_dat$Loser))
  game_dat <- game_dat %>% mutate(Loser = gsub("9", "", game_dat$Loser))
  game_dat <- game_dat %>% mutate(Loser = gsub("0", "", game_dat$Loser))
  game_dat <- game_dat %>% mutate(Loser = gsub(")", "", game_dat$Loser))
  
  game_dat <- game_dat %>% mutate(X8 = ifelse(is.na(X8 == TRUE), "vs", "@"))
  game_dat <- game_dat %>% mutate(Home = ifelse(X8 == '@', Loser, Winner))
  game_dat <- game_dat %>% mutate(Away = ifelse(Home == Winner, Loser, Winner))
  game_dat <- game_dat %>% mutate(Outcome = factor(ifelse(Home == Winner, 1, 0)))
  game_dat <- game_dat %>% mutate(Year = year)
  game_dat <- game_dat %>% select(Wk, Year, Home, Away, Outcome)
}  

game_dat_2008 <- formatter_game1(game_dat_2008, 2008)
game_dat_2009 <- formatter_game1(game_dat_2009, 2009)
game_dat_2010 <- formatter_game1(game_dat_2010, 2010)
game_dat_2011 <- formatter_game1(game_dat_2011, 2011)
game_dat_2012 <- formatter_game1(game_dat_2012, 2012)
game_dat_2013 <- formatter_game2(game_dat_2013, 2013)
game_dat_2014 <- formatter_game2(game_dat_2014, 2014)
game_dat_2015 <- formatter_game2(game_dat_2015, 2015)
game_dat_2016 <- formatter_game2(game_dat_2016, 2016)
game_dat_2017 <- formatter_game2(game_dat_2017, 2017)
game_dat_2018 <- formatter_game2(game_dat_2018, 2018)
```
  
```{r}
# This chunk simply prepares team names for a join in all files by trimming white space surrounding the strings.

game_dat_2018 <- game_dat_2018 %>% mutate(Home = trimws(Home),
                                          Away = trimws(Away))
off_dat_2018 <- off_dat_2018 %>% mutate(Home = trimws(Home))
def_dat_2018 <- def_dat_2018 %>% mutate(Home = trimws(Home))

game_dat_2017 <- game_dat_2017 %>% mutate(Home = trimws(Home),
                                          Away = trimws(Away))
off_dat_2017 <- off_dat_2017 %>% mutate(Home = trimws(Home))
def_dat_2017 <- def_dat_2017 %>% mutate(Home = trimws(Home))

game_dat_2016 <- game_dat_2016 %>% mutate(Home = trimws(Home),
                                          Away = trimws(Away))
off_dat_2016 <- off_dat_2016 %>% mutate(Home = trimws(Home))
def_dat_2016 <- def_dat_2016 %>% mutate(Home = trimws(Home))

game_dat_2015 <- game_dat_2015 %>% mutate(Home = trimws(Home),
                                          Away = trimws(Away))
off_dat_2015 <- off_dat_2015 %>% mutate(Home = trimws(Home))
def_dat_2015 <- def_dat_2015 %>% mutate(Home = trimws(Home))

game_dat_2014 <- game_dat_2014 %>% mutate(Home = trimws(Home),
                                          Away = trimws(Away))
off_dat_2014 <- off_dat_2014 %>% mutate(Home = trimws(Home))
def_dat_2014 <- def_dat_2014 %>% mutate(Home = trimws(Home))

game_dat_2013 <- game_dat_2013 %>% mutate(Home = trimws(Home),
                                          Away = trimws(Away))
off_dat_2013 <- off_dat_2013 %>% mutate(Home = trimws(Home))
def_dat_2013 <- def_dat_2013 %>% mutate(Home = trimws(Home))

game_dat_2012 <- game_dat_2012 %>% mutate(Home = trimws(Home),
                                          Away = trimws(Away))
off_dat_2012 <- off_dat_2012 %>% mutate(Home = trimws(Home))
def_dat_2012 <- def_dat_2012 %>% mutate(Home = trimws(Home))

game_dat_2011 <- game_dat_2011 %>% mutate(Home = trimws(Home),
                                          Away = trimws(Away))
off_dat_2011 <- off_dat_2011 %>% mutate(Home = trimws(Home))
def_dat_2011 <- def_dat_2011 %>% mutate(Home = trimws(Home))

game_dat_2010 <- game_dat_2010 %>% mutate(Home = trimws(Home),
                                          Away = trimws(Away))
off_dat_2010 <- off_dat_2010 %>% mutate(Home = trimws(Home))
def_dat_2010 <- def_dat_2010 %>% mutate(Home = trimws(Home))

game_dat_2009 <- game_dat_2009 %>% mutate(Home = trimws(Home),
                                          Away = trimws(Away))
off_dat_2009 <- off_dat_2009 %>% mutate(Home = trimws(Home))
def_dat_2009 <- def_dat_2009 %>% mutate(Home = trimws(Home))

game_dat_2008 <- game_dat_2008 %>% mutate(Home = trimws(Home),
                                          Away = trimws(Away))
off_dat_2008 <- off_dat_2008 %>% mutate(Home = trimws(Home))
def_dat_2008 <- def_dat_2008 %>% mutate(Home = trimws(Home))

```


```{r}
# These functions modify some team names from the game data table.  In our offense and defensive tables the team names were sometimes presented with slightly different representations of the same team, and therefore we needed to reformat one in order for joins to work properly.

fix_up_home <- function(dat) {
  dat <- dat %>% mutate(Home = trimws(Home), 
                        Away = trimws(Away), 
                        Home = ifelse(Home == "Alabama-Birmingham", "UAB",
                               ifelse(Home == "Miami OH", "Miami (OH)",
                               ifelse(Home == "Mississippi", "Ole Miss",
                               ifelse(Home == "Texas-El Paso", "UTEP", 
                               ifelse(Home == "Pittsburgh", "Pitt",
                               ifelse(Home == "Southern California", "USC",
                               ifelse(Home == "Louisiana State", "LSU",
                               ifelse(Home == "Southern Methodist", "SMU",
                               ifelse(Home == "Texas-San Antonio", "UTSA",
                               ifelse(Home == "Central Florida", "UCF",
                               ifelse(Home == "Miami FL", "Miami (FL)",
                               ifelse(Home == "Nevada-Las Vegas", "UNLV", Home)))))))))))))
}

fix_up_away <- function(dat) {
  dat <- dat %>% mutate(Home = trimws(Home), 
                        Away = trimws(Away), 
                        Away = ifelse(Away == "Alabama-Birmingham", "UAB",
                               ifelse(Away == "Miami OH", "Miami (OH)",
                               ifelse(Away == "Mississippi", "Ole Miss",
                               ifelse(Away == "Texas-El Paso", "UTEP", 
                               ifelse(Away == "Pittsburgh", "Pitt",
                               ifelse(Away == "Southern California", "USC",
                               ifelse(Away == "Louisiana State", "LSU",
                               ifelse(Away == "Southern Methodist", "SMU",
                               ifelse(Away == "Texas-San Antonio", "UTSA",
                               ifelse(Away == "Central Florida", "UCF",
                               ifelse(Away == "Miami FL", "Miami (FL)",
                               ifelse(Away == "Nevada-Las Vegas", "UNLV", Away)))))))))))))
}

game_dat_2018 <- fix_up_home(game_dat_2018)
game_dat_2018 <- fix_up_away(game_dat_2018)

game_dat_2017 <- fix_up_home(game_dat_2017)
game_dat_2017 <- fix_up_away(game_dat_2017)

game_dat_2016 <- fix_up_home(game_dat_2016)
game_dat_2016 <- fix_up_away(game_dat_2016)

game_dat_2015 <- fix_up_home(game_dat_2015)
game_dat_2015 <- fix_up_away(game_dat_2015)

game_dat_2014 <- fix_up_home(game_dat_2014)
game_dat_2014 <- fix_up_away(game_dat_2014)

game_dat_2013 <- fix_up_home(game_dat_2013)
game_dat_2013 <- fix_up_away(game_dat_2013)

game_dat_2012 <- fix_up_home(game_dat_2012)
game_dat_2012 <- fix_up_away(game_dat_2012)

game_dat_2011 <- fix_up_home(game_dat_2011)
game_dat_2011 <- fix_up_away(game_dat_2011)

game_dat_2010 <- fix_up_home(game_dat_2010)
game_dat_2010 <- fix_up_away(game_dat_2010)

game_dat_2009 <- fix_up_home(game_dat_2009)
game_dat_2009 <- fix_up_away(game_dat_2009)

game_dat_2008 <- fix_up_home(game_dat_2008)
game_dat_2008 <- fix_up_away(game_dat_2008)
```

```{r}
# This chunk simply joins the offensive and defensive data for all years.

team_dat_2018 <- full_join(off_dat_2018, def_dat_2018, "Home")
team_dat_2017 <- full_join(off_dat_2017, def_dat_2017, "Home")
team_dat_2016 <- full_join(off_dat_2016, def_dat_2016, "Home")
team_dat_2015 <- full_join(off_dat_2015, def_dat_2015, "Home")
team_dat_2014 <- full_join(off_dat_2014, def_dat_2014, "Home")
team_dat_2013 <- full_join(off_dat_2013, def_dat_2013, "Home")
team_dat_2012 <- full_join(off_dat_2012, def_dat_2012, "Home")
team_dat_2011 <- full_join(off_dat_2011, def_dat_2011, "Home")
team_dat_2010 <- full_join(off_dat_2010, def_dat_2010, "Home")
team_dat_2009 <- full_join(off_dat_2009, def_dat_2009, "Home")
team_dat_2008 <- full_join(off_dat_2008, def_dat_2008, "Home")
```

```{r}
game_dat_2018 <- full_join(game_dat_2018, team_dat_2018, "Home")
game_dat_2017 <- full_join(game_dat_2017, team_dat_2017, "Home")
game_dat_2016 <- full_join(game_dat_2016, team_dat_2016, "Home")
game_dat_2015 <- full_join(game_dat_2015, team_dat_2015, "Home")
game_dat_2014 <- full_join(game_dat_2014, team_dat_2014, "Home")
game_dat_2013 <- full_join(game_dat_2013, team_dat_2013, "Home")
game_dat_2012 <- full_join(game_dat_2012, team_dat_2012, "Home")
game_dat_2011 <- full_join(game_dat_2011, team_dat_2011, "Home")
game_dat_2010 <- full_join(game_dat_2010, team_dat_2010, "Home")
game_dat_2009 <- full_join(game_dat_2009, team_dat_2009, "Home")
game_dat_2008 <- full_join(game_dat_2008, team_dat_2008, "Home")
```


```{r}
reformat <- function(dat) {
  dat <- dat %>% rename(Away = Home)
}

team_dat_2018 <- reformat(team_dat_2018)
team_dat_2017 <- reformat(team_dat_2017)
team_dat_2016 <- reformat(team_dat_2016)
team_dat_2015 <- reformat(team_dat_2015)
team_dat_2014 <- reformat(team_dat_2014)
team_dat_2013 <- reformat(team_dat_2013)
team_dat_2012 <- reformat(team_dat_2012)
team_dat_2011 <- reformat(team_dat_2011)
team_dat_2010 <- reformat(team_dat_2010)
team_dat_2009 <- reformat(team_dat_2009)
team_dat_2008 <- reformat(team_dat_2008)
```

```{r}
game_dat_2018 <- full_join(game_dat_2018, team_dat_2018, "Away")
game_dat_2017 <- full_join(game_dat_2017, team_dat_2017, "Away")
game_dat_2016 <- full_join(game_dat_2016, team_dat_2016, "Away")
game_dat_2015 <- full_join(game_dat_2015, team_dat_2015, "Away")
game_dat_2014 <- full_join(game_dat_2014, team_dat_2014, "Away")
game_dat_2013 <- full_join(game_dat_2013, team_dat_2013, "Away")
game_dat_2012 <- full_join(game_dat_2012, team_dat_2012, "Away")
game_dat_2011 <- full_join(game_dat_2011, team_dat_2011, "Away")
game_dat_2010 <- full_join(game_dat_2010, team_dat_2010, "Away")
game_dat_2009 <- full_join(game_dat_2009, team_dat_2009, "Away")
game_dat_2008 <- full_join(game_dat_2008, team_dat_2008, "Away")
```



```{r}
game_dat_2018 <- game_dat_2018 %>% na.omit()
game_dat_2017 <- game_dat_2017 %>% na.omit()
game_dat_2016 <- game_dat_2016 %>% na.omit()
game_dat_2015 <- game_dat_2015 %>% na.omit()
game_dat_2014 <- game_dat_2014 %>% na.omit()
game_dat_2013 <- game_dat_2013 %>% na.omit()
game_dat_2012 <- game_dat_2012 %>% na.omit()
game_dat_2011 <- game_dat_2011 %>% na.omit()
game_dat_2010 <- game_dat_2010 %>% na.omit()
game_dat_2009 <- game_dat_2009 %>% na.omit()
game_dat_2008 <- game_dat_2008 %>% na.omit()
```


```{r}
conference_list <- conference_list %>% rename(Home = School)

game_dat_2018 <- full_join(game_dat_2018, conference_list, "Home")

game_dat_2018 <- game_dat_2018 %>% rename(Home_conf = conf)

conference_list <- conference_list %>% rename(Away = Home)

game_dat_2018 <- full_join(game_dat_2018, conference_list, "Away")

game_dat_2018 <- game_dat_2018 %>% rename(Away_conf = conf)

colnames(game_dat_2018)
```










**Structure Variables Properly**

```{r}
game_dat_2018 <- game_dat_2018 %>% mutate(Wk = factor(Wk),
                                          Year = factor(Year),
                                          Home = factor(Home),
                                          Away = factor(Away))

game_dat_2017 <- game_dat_2017 %>% mutate(Wk = factor(Wk),
                                          Year = factor(Year),
                                          Home = factor(Home),
                                          Away = factor(Away))

game_dat_2016 <- game_dat_2016 %>% mutate(Wk = factor(Wk),
                                          Year = factor(Year),
                                          Home = factor(Home),
                                          Away = factor(Away))

game_dat_2015 <- game_dat_2015 %>% mutate(Wk = factor(Wk),
                                          Year = factor(Year),
                                          Home = factor(Home),
                                          Away = factor(Away))

game_dat_2014 <- game_dat_2014 %>% mutate(Wk = factor(Wk),
                                          Year = factor(Year),
                                          Home = factor(Home),
                                          Away = factor(Away))

game_dat_2013 <- game_dat_2013 %>% mutate(Wk = factor(Wk),
                                          Year = factor(Year),
                                          Home = factor(Home),
                                          Away = factor(Away))

game_dat_2012 <- game_dat_2012 %>% mutate(Wk = factor(Wk),
                                          Year = factor(Year),
                                          Home = factor(Home),
                                          Away = factor(Away))

game_dat_2011 <- game_dat_2011 %>% mutate(Wk = factor(Wk),
                                          Year = factor(Year),
                                          Home = factor(Home),
                                          Away = factor(Away))

game_dat_2010 <- game_dat_2010 %>% mutate(Wk = factor(Wk),
                                          Year = factor(Year),
                                          Home = factor(Home),
                                          Away = factor(Away))

game_dat_2009 <- game_dat_2009 %>% mutate(Wk = factor(Wk),
                                          Year = factor(Year),
                                          Home = factor(Home),
                                          Away = factor(Away))

game_dat_2008 <- game_dat_2008 %>% mutate(Wk = factor(Wk),
                                          Year = factor(Year),
                                          Home = factor(Home),
                                          Away = factor(Away))
```




**Explore the Data**

```{r}
write_csv(game_dat_2008, "game_data/game_dat_2008.csv")
write_csv(game_dat_2009, "game_data/game_dat_2009.csv")
write_csv(game_dat_2010, "game_data/game_dat_2010.csv")
write_csv(game_dat_2011, "game_data/game_dat_2011.csv")
write_csv(game_dat_2012, "game_data/game_dat_2012.csv")
write_csv(game_dat_2013, "game_data/game_dat_2013.csv")
write_csv(game_dat_2014, "game_data/game_dat_2014.csv")
write_csv(game_dat_2015, "game_data/game_dat_2015.csv")
write_csv(game_dat_2016, "game_data/game_dat_2016.csv")
write_csv(game_dat_2017, "game_data/game_dat_2017.csv")
write_csv(game_dat_2018, "game_data/game_dat_2018.csv")
```







